version: '3'

tasks:
  build:
    cmds:
      - echo "Building..."
      - wails build
      - echo "Done!"

  dev:
    cmds:
      - echo "Starting dev app..."
      - wails dev
      - echo "Done!"

  migrate:up:
    cmds:
      - echo "Migrating..."
      - migrate -path ./migrations -database sqlite3://assets/db/tasks.db up
      - echo "Done!"

  migrate:down:
    cmds:
      - echo "Rolling back..."
      - migrate -path ./migrations -database sqlite3://assets/db/tasks.db down
      - echo "Done!"